[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/otf"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/fonts/*.otf"
    [headers.values]
    Content-Type = "font/otf"

[[headers]]
  for = "/fonts/*.woff"
    [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/fonts/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"